name: Build, Pack & Publish

on:
  push:
    branches:
      - master
      - net5

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET SDK 6.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Ensure .NET 6 Runtime is Installed
        run: |
          curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --runtime dotnet --version 6.0.29
          echo "$HOME/.dotnet" >> $GITHUB_PATH
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Get the sources
        uses: actions/checkout@v2

      - name: Extract release notes
        run: |
          git log --pretty=format:'%s' ${GITHUB_REF} | perl -pe 's| \(.*tag: v(\d+.\d+.\d+(-preview\d{3})?)(, .*?)*\)|\n## \1\n|g' > RELEASE-NOTES.txt

      - name: Run the build script
        uses: cake-build/cake-action@v1
        with:
          script-path: build.cake
          target: Pack
          cake-version: 1.1.0
          cake-bootstrap: true

      # Publish NuGet packages
      - name: Publish Solnett.Extensions on version change
        uses: brunopedrazza/publish-nuget@master
        with:
          PROJECT_FILE_PATH: src/Solnet.Extensions/Solnet.Extensions.csproj
          PACKAGE_NAME: Solnett.Extensions
          VERSION_FILE_PATH: SharedBuildProperties.props
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_FORMAT: v*
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          INCLUDE_SYMBOLS: true

      - name: Publish Solnett.Wallet on version change
        uses: brunopedrazza/publish-nuget@master
        with:
          PROJECT_FILE_PATH: src/Solnet.Wallet/Solnet.Wallet.csproj
          PACKAGE_NAME: Solnett.Wallet
          VERSION_FILE_PATH: SharedBuildProperties.props
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_FORMAT: v*
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          INCLUDE_SYMBOLS: true

      - name: Publish Solnett.Rpc on version change
        uses: brunopedrazza/publish-nuget@master
        with:
          PROJECT_FILE_PATH: src/Solnet.Rpc/Solnet.Rpc.csproj
          PACKAGE_NAME: Solnett.Rpc
          VERSION_FILE_PATH: SharedBuildProperties.props
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_FORMAT: v*
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          INCLUDE_SYMBOLS: true

      - name: Publish Solnett.KeyStore on version change
        uses: brunopedrazza/publish-nuget@master
        with:
          PROJECT_FILE_PATH: src/Solnet.KeyStore/Solnet.KeyStore.csproj
          PACKAGE_NAME: Solnett.KeyStore
          VERSION_FILE_PATH: SharedBuildProperties.props
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_FORMAT: v*
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          INCLUDE_SYMBOLS: true

      - name: Publish Solnett.Programs on version change
        id: publish_nuget
        uses: brunopedrazza/publish-nuget@master
        with:
          PROJECT_FILE_PATH: src/Solnet.Programs/Solnet.Programs.csproj
          PACKAGE_NAME: Solnett.Programs
          VERSION_FILE_PATH: SharedBuildProperties.props
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_FORMAT: v*
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          INCLUDE_SYMBOLS: true

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.publish_nuget.outputs.VERSION }}
          release_name: ${{ steps.publish_nuget.outputs.VERSION }}
          body_path: RELEASE-NOTES.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload release assets
      - name: Upload Solnett.Extensions release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/Solnet.Extensions.dll
          tag: ${{ steps.publish_nuget.outputs.VERSION }}
          upload_url: ${{ steps.create_release.outputs.upload_url }}

      - name: Upload Solnett.Wallet release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/Solnet.Wallet.dll
          tag: ${{ steps.publish_nuget.outputs.VERSION }}
          upload_url: ${{ steps.create_release.outputs.upload_url }}

      - name: Upload Solnett.Rpc release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/Solnet.Rpc.dll
          tag: ${{ steps.publish_nuget.outputs.VERSION }}
          upload_url: ${{ steps.create_release.outputs.upload_url }}

      - name: Upload Solnett.KeyStore release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/Solnet.KeyStore.dll
          tag: ${{ steps.publish_nuget.outputs.VERSION }}
          upload_url: ${{ steps.create_release.outputs.upload_url }}

      - name: Upload Solnett.Programs release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/Solnet.Programs.dll
          tag: ${{ steps.publish_nuget.outputs.VERSION }}
          upload_url: ${{ steps.create_release.outputs.upload_url }}